
#server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: marcos12345
  jpa:
    show-sql: true  # serve para mostrar o log dos comandos do sql no console
    hibernate:
      ddl-auto: update # serve para a cada vez que eu fechar e abrir o servidor, ele compara se tem algo difrente e atualiza
      #drop - serve para começar a tabela do zero (nunca fazer isso no trabalho)
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace